<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\MyRecipBook.Communication\MyRecipeBook.Communication.csproj" />
    <ProjectReference Include="..\..\Shared\MyRecipBook.Exceptions\MyRecipeBook.Exceptions.csproj" />
    <ProjectReference Include="..\MyRecipBook.Domain\MyRecipeBook.Domain.csproj" />
  </ItemGroup>

</Project>
